/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CategoryTransformer from '#transformers/category_transformer'
import type ItemTransformer from '#transformers/item_transformer'
import type StockTransactionTransformer from '#transformers/stock_transaction_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Category = InferData<CategoryTransformer>
  export namespace Category {
    export type Variants = InferVariants<CategoryTransformer>
  }
  export type Item = InferData<ItemTransformer>
  export namespace Item {
    export type Variants = InferVariants<ItemTransformer>
  }
  export type StockTransaction = InferData<StockTransactionTransformer>
  export namespace StockTransaction {
    export type Variants = InferVariants<StockTransactionTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
